version: '3.4'


services:
  producer:
    image: producer-api
    build:
      context: .
      dockerfile: UserRabbitMqExample.Producer/Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    ports:
      - 5000:5000
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=db.db"
      ASPNETCORE_ENVIRONMENT: "Production"
      ProducerHost: rabbitmq
      ASPNETCORE_URLS: "http://+:5000"


  subscriber:
    image: subscriber-cli
    build:
      context: .
      dockerfile: UserRabbitMqExample.Subscriber/Dockerfile
    depends_on:
      - rabbitmq
    restart: always
    environment:
      SubscriberHost: rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"